use_frameworks!

platform :ios, '10.0'

target 'WSTestCocoa_Example' do
  pod 'WSTestCocoa', :path => '../'

  target 'WSTestCocoa_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
